# -*- coding: utf-8 -*-
"""Proyek Analisis Data.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ug4Ox4qIFDSo1koFA0XiNJE-ce12rECy

# Proyek Analisis Data: [Input Nama Dataset]
- **Nama:** Muchamad Naufal Aziz
- **Email:** aziznaufal804@gmail.com
- **ID Dicoding:** azizprogam

## Menentukan Pertanyaan Bisnis

- Bagaimana pengaruh cuaca terhadap pola peminjaman sepeda, dengan mempertimbangkan suhu udara (temp), kelembaban (hum), dan kecepatan angin (windspeed) terhadap jumlah peminjaman sepeda (cnt) pada hari-hari libur dan hari kerja?
- Apakah terdapat pola musiman yang jelas dalam tren peminjaman sepeda, dengan mempertimbangkan musim (season) dan bulan (mnth), serta bagaimana pengaruhnya terhadap jumlah peminjaman sepeda (cnt) pada jam-jam tertentu dalam sehari (hr)?

## Import Semua Packages/Library yang Digunakan
"""

import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

"""## Data Wrangling

### Gathering Data
"""

import pandas as pd

def gather_data(file_path):
    try:
        # Membaca data dari file CSV
        df = pd.read_csv(file_path, usecols=['instant', 'dteday', 'season', 'yr', 'mnth',
                                             'holiday', 'weekday', 'workingday', 'weathersit',
                                             'temp', 'atemp', 'hum', 'windspeed',
                                             'casual', 'registered', 'cnt'])
        return df
    except FileNotFoundError:
        print(f"File {file_path} not found.")
        return None
    except Exception as e:
        print(f"An error occurred: {e}")
        return None

def main():
    file_path = 'hour.csv'
    print("Gathering Data...")
    df = gather_data(file_path)

    if df is not None:
        print("Data berhasil dikumpulkan:")
        print(df.head())

if __name__ == "__main__":
    main()

"""### Assessing Data"""

import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

# Membaca data dari file CSV
df = pd.read_csv('hour.csv')

# Menampilkan informasi umum tentang dataset
print("Informasi Data:")
print(df.info())

# Menampilkan statistik deskriptif untuk data numerik
print("\nStatistik Deskriptif:")
print(df.describe())

# Menampilkan beberapa contoh data
print("\nContoh Data:")
print(df.head())

# Menampilkan jumlah nilai yang unik untuk setiap kolom
print("\nJumlah Nilai Unik untuk Setiap Kolom:")
print(df.nunique())

# Memeriksa nilai-nilai yang hilang
print("\nTotal Nilai Hilang untuk Setiap Kolom:")
print(df.isnull().sum())

# Memeriksa nilai-nilai yang duplikat
print("\nTotal Nilai Duplikat:")
print(df.duplicated().sum())

# Memeriksa korelasi antara variabel numerik
print("\nKorelasi Antara Variabel Numerik:")
numeric_cols = ['temp', 'atemp', 'hum', 'windspeed', 'casual', 'registered', 'cnt']
numeric_df = df[numeric_cols]
corr = numeric_df.corr()
plt.figure(figsize=(10, 8))
sns.heatmap(corr, annot=True, cmap='coolwarm', fmt=".2f", linewidths=0.5)
plt.title('Korelasi Antar Variabel Numerik')
plt.show()

"""### Cleaning Data"""

import pandas as pd

# Membaca data dari file CSV
df = pd.read_csv('hour.csv')

# Menampilkan lima baris pertama dari data sebelum pembersihan
print("Data sebelum pembersihan:")
print(df.head())


# Memeriksa dan mengatasi nilai-nilai duplikat
num_duplicates = df.duplicated().sum()
if num_duplicates > 0:
    print(f"Jumlah nilai duplikat sebelum penghapusan: {num_duplicates}")
    df.drop_duplicates(inplace=True)
    print("Nilai duplikat telah dihapus.")

# Memeriksa dan mengatasi nilai-nilai yang hilang (NaN)
# Menghitung jumlah nilai yang hilang untuk setiap kolom
missing_values = df.isnull().sum()
print("\nJumlah nilai yang hilang untuk setiap kolom:")
print(missing_values)

# Menggantikan nilai-nilai yang hilang dengan nilai rata-rata kolom
numeric_cols = df.select_dtypes(include='number').columns
df[numeric_cols] = df[numeric_cols].fillna(df[numeric_cols].mean())

# Menampilkan lima baris pertama dari data setelah pembersihan
print("\nData setelah pembersihan:")
print(df.head())

"""## Exploratory Data Analysis (EDA)

### Explore ...
"""

import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

# Membaca data dari file CSV
df = pd.read_csv('hour.csv')

# Menampilkan lima baris pertama dari data
print("Data Head:")
print(df.head())

# Informasi umum tentang dataset
print("\nInformasi Dataset:")
print(df.info())

# Statistik deskriptif untuk data numerik
print("\nStatistik Deskriptif untuk Data Numerik:")
print(df.describe())

# Jumlah nilai unik untuk setiap kolom
print("\nJumlah Nilai Unik untuk Setiap Kolom:")
print(df.nunique())

# Memeriksa nilai-nilai yang hilang
print("\nTotal Nilai Hilang untuk Setiap Kolom:")
print(df.isnull().sum())

# Memeriksa nilai-nilai yang duplikat
print("\nTotal Nilai Duplikat:")
print(df.duplicated().sum())

# Visualisasi distribusi variabel numerik
plt.figure(figsize=(15, 10))
numeric_cols = ['temp', 'atemp', 'hum', 'windspeed', 'casual', 'registered', 'cnt']
for i, col in enumerate(numeric_cols, 1):
    plt.subplot(3, 3, i)
    sns.histplot(df[col], bins=20, kde=True)
    plt.title(f'Distribusi {col}')
plt.tight_layout()
plt.show()

# Korelasi antar variabel numerik
plt.figure(figsize=(10, 8))
sns.heatmap(df[numeric_cols].corr(), annot=True, cmap='coolwarm', fmt=".2f", linewidths=0.5)
plt.title('Korelasi Antar Variabel Numerik')
plt.show()

# Visualisasi relasi antara variabel numerik
sns.pairplot(df[numeric_cols])
plt.suptitle('Scatter Plot Antar Variabel Numerik', y=1.02)
plt.show()

"""## Visualization & Explanatory Analysis

### Pertanyaan 1:
"""

import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

# Membaca data dari file CSV
df = pd.read_csv('hour.csv')

# Memastikan tipe data kolom dteday adalah datetime
df['dteday'] = pd.to_datetime(df['dteday'])

# Menambahkan kolom baru untuk menandai hari kerja dan hari libur
df['is_holiday'] = df['holiday'].apply(lambda x: 'Holiday' if x == 1 else 'Working Day')

# Memilih kolom yang akan digunakan untuk analisis
selected_columns = ['dteday', 'temp', 'hum', 'windspeed', 'cnt', 'is_holiday']
df_selected = df[selected_columns]

# Menampilkan hubungan antara suhu, kelembaban, dan kecepatan angin terhadap jumlah peminjaman sepeda
plt.figure(figsize=(15, 10))
sns.pairplot(df_selected, hue='is_holiday', vars=['temp', 'hum', 'windspeed', 'cnt'], diag_kind='kde')
plt.suptitle('Hubungan antara Suhu, Kelembaban, dan Kecepatan Angin dengan Jumlah Peminjaman Sepeda', y=1.02)
plt.show()

"""Analisis Visual: Hubungan Antara Cuaca dan Peminjaman Sepeda

Visualisasi ini memberikan gambaran tentang bagaimana hubungan antara faktor cuaca (suhu udara, kelembaban, dan kecepatan angin) dengan jumlah peminjaman sepeda, dengan mempertimbangkan apakah hari tersebut merupakan hari libur atau hari kerja.

Suhu Udara (Temp):

Terlihat bahwa pada hari-hari dengan suhu udara yang tinggi, jumlah peminjaman sepeda cenderung meningkat. Ini menunjukkan bahwa cuaca yang lebih hangat mungkin mendorong orang untuk menggunakan sepeda lebih sering.
Pada hari libur, distribusi jumlah peminjaman sepeda lebih merata di berbagai rentang suhu, sementara pada hari kerja, terdapat konsentrasi peminjaman sepeda yang lebih tinggi pada suhu udara yang lebih rendah.
Kelembaban (Humidity):

Tidak terlihat pola yang jelas antara kelembaban udara dan jumlah peminjaman sepeda. Distribusi jumlah peminjaman sepeda cenderung seragam di berbagai tingkat kelembaban.
Pada hari libur, ada kecenderungan sedikit meningkatnya jumlah peminjaman sepeda pada kelembaban yang lebih rendah, tetapi pada hari kerja, distribusi jumlah peminjaman sepeda lebih merata di berbagai tingkat kelembaban.
Kecepatan Angin (Windspeed):

Tidak terlihat pola yang jelas antara kecepatan angin dan jumlah peminjaman sepeda. Distribusi jumlah peminjaman sepeda cenderung seragam di berbagai tingkat kecepatan angin.
Pada hari libur maupun hari kerja, tidak ada perbedaan yang signifikan dalam distribusi jumlah peminjaman sepeda pada berbagai tingkat kecepatan angin.
Kesimpulan:
Dari visualisasi ini, kita dapat menyimpulkan bahwa suhu udara memiliki pengaruh yang signifikan terhadap pola peminjaman sepeda, dengan kecenderungan peningkatan peminjaman pada suhu yang lebih tinggi. Namun, faktor-faktor lain seperti kelembaban dan kecepatan angin mungkin tidak memiliki pengaruh yang signifikan pada pola peminjaman sepeda. Selain itu, tidak terlihat perbedaan pola peminjaman sepeda yang signifikan antara hari libur dan hari kerja berdasarkan faktor cuaca.

### Pertanyaan 2:
"""

import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

# Membaca data dari file CSV
df = pd.read_csv('hour.csv')

# Menambahkan kolom bulan (month) berdasarkan kolom mnth
df['month'] = df['mnth'].map({1: 'Jan', 2: 'Feb', 3: 'Mar', 4: 'Apr', 5: 'May', 6: 'Jun', 7: 'Jul', 8: 'Aug', 9: 'Sep', 10: 'Oct', 11: 'Nov', 12: 'Dec'})

# Memilih kolom yang akan digunakan untuk analisis
selected_columns = ['season', 'month', 'hr', 'cnt']
df_selected = df[selected_columns]

# Menghitung jumlah peminjaman sepeda rata-rata berdasarkan musim, bulan, dan jam
pivot_table = df_selected.pivot_table(index=['season', 'month'], columns='hr', values='cnt', aggfunc='mean')

# Membuat heatmap untuk menampilkan tren peminjaman sepeda berdasarkan musim, bulan, dan jam
plt.figure(figsize=(15, 10))
sns.heatmap(pivot_table, cmap='viridis', annot=True, fmt=".0f")
plt.title('Pola Musiman dalam Tren Peminjaman Sepeda per Jam')
plt.xlabel('Jam (hr)')
plt.ylabel('Musim dan Bulan')
plt.show()

"""Tentu, berikut adalah penjelasan tertulis dan kesimpulan dari hasil visualisasi dan analisis yang dilakukan:

Visualisasi & Analisis Eksplanatori: Pola Musiman dalam Tren Peminjaman Sepeda

Visualisasi ini bertujuan untuk menganalisis apakah terdapat pola musiman yang jelas dalam tren peminjaman sepeda, dengan mempertimbangkan musim (season) dan bulan (mnth), serta bagaimana pengaruhnya terhadap jumlah peminjaman sepeda (cnt) pada jam-jam tertentu dalam sehari (hr).

Penjelasan Tertulis:

Heatmap Visualisasi:
Heatmap menampilkan tren peminjaman sepeda per jam dalam sehari, diurutkan berdasarkan musim dan bulan.
Warna yang lebih gelap menunjukkan jumlah peminjaman yang lebih tinggi, sedangkan warna yang lebih terang menunjukkan jumlah peminjaman yang lebih rendah.
Pada sumbu x (hr), jam-jam dalam sehari ditampilkan dari 0 hingga 23.
Pada sumbu y, musim dan bulan ditampilkan, dimulai dari musim 1 (Musim Semi) hingga musim 4 (Musim Dingin), dengan bulan-bulan masing-masing musim.

## Conclusion

- Conclution pertanyaan 1
Pengaruh Suhu Udara Terhadap Peminjaman Sepeda:

Terdapat hubungan yang signifikan antara suhu udara dan jumlah peminjaman sepeda. Pada suhu yang lebih tinggi, jumlah peminjaman sepeda cenderung meningkat, menunjukkan bahwa cuaca yang lebih hangat mendorong orang untuk menggunakan sepeda lebih sering.
Pengaruh Faktor Kelembaban dan Kecepatan Angin:

Tidak terlihat pola yang jelas antara kelembaban udara atau kecepatan angin dengan jumlah peminjaman sepeda. Distribusi jumlah peminjaman sepeda cenderung seragam di berbagai tingkat kelembaban dan kecepatan angin.
Perbedaan Pola Peminjaman pada Hari Libur dan Hari Kerja:

Tidak terdapat perbedaan yang signifikan dalam pola peminjaman sepeda antara hari libur dan hari kerja berdasarkan faktor cuaca. Distribusi jumlah peminjaman sepeda cenderung seragam di berbagai tingkat kelembaban, kecepatan angin, dan suhu udara baik pada hari libur maupun hari kerja.

- Conclution pertanyaan 2 Apakah terdapat pola musiman yang jelas dalam tren peminjaman sepeda, dengan mempertimbangkan musim (season) dan bulan (mnth), serta bagaimana pengaruhnya terhadap jumlah peminjaman sepeda (cnt) pada jam-jam tertentu dalam sehari (hr)?

Pola Musiman:
Terdapat pola musiman yang jelas dalam tren peminjaman sepeda. Peminjaman sepeda cenderung meningkat saat musim semi dan musim panas, sementara cenderung menurun saat musim gugur dan musim dingin.
Pola ini terlihat secara konsisten di seluruh jam dalam sehari.
Puncak peminjaman sepeda terjadi pada bulan-bulan musim panas, terutama pada jam-jam sore dan sore hari.
Jumlah peminjaman sepeda cenderung lebih rendah pada bulan-bulan musim dingin, dengan penurunan yang lebih tajam terutama pada jam-jam pagi dan malam.
"""